Numpy Array operations


In [1]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[8,9,10],
                [4,5,6],[15,16,17]])
print("basic Indexing:",arr[1,2],arr[2,2])

basic slicing: 10 6


In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic Slicing ",arr[2:7],arr[2:8])

basic Slicing  [3 4 5 6 7] [3 4 5 6 7 8]


In [18]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print("basic indexing ", arr[2,2])
print("basic Slicing ", arr[0:3,0:2])
print("basic Slicing ", arr[0:2,0:3])
print(arr[1])
print(arr[:,1])

basic indexing  9
basic Slicing  [[1 2]
 [4 5]
 [7 8]]
basic Slicing  [[1 2 3]
 [4 5 6]]
[4 5 6]
[2 5 8]


SORTING

In [21]:
unsorted = np.array([1,5,3,7,8,3,2,4,6,10,9])
unsorted.sort()
print("sorted array :", unsorted[:])
unsorted1 = np.array([1,5,3,7,8,3,2,4,6,10,9])
print("sorted array ",np.sort(unsorted1))

sorted array : [ 1  2  3  3  4  5  6  7  8  9 10]
sorted array  [ 1  2  3  3  4  5  6  7  8  9 10]


In [25]:
arr_2d_unsorted = np.array([[3,1],
                           [1,2],
                           [2,1]])
print("column wise sorted array:\n ", np.sort(arr_2d_unsorted,axis = 0))
print("row wise sorted array:\n ", np.sort(arr_2d_unsorted,axis = 1))

column wise sorted array:
  [[1 1]
 [2 1]
 [3 2]]
row wise sorted array:
  [[1 3]
 [1 2]
 [1 2]]


Filtering and Filtering by mask

In [31]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
print("even numbers in numbers : ",numbers[numbers%2==0])
mask = numbers > 5
print(mask)
print(" numbers > 5 in numbers : ",numbers[mask])


even numbers in numbers :  [ 2  4  6  8 10]
[False False False False False  True  True  True  True  True]
 numbers > 5 in numbers :  [ 6  7  8  9 10]


fancy indexing and np.where()

In [30]:
indices = [0,2,4,6,8]
print("fancy indexing : ", numbers[indices])

where_use_case = np.where(numbers > 5)
print(where_use_case)
print("result using where ",numbers[where_use_case])

fancy indexing :  [1 3 5 7 9]
(array([5, 6, 7, 8, 9]),)
result using where  [ 6  7  8  9 10]


In [35]:
np.linspace(0, 10, 4, endpoint=False)

array([0. , 2.5, 5. , 7.5])

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
conditional_array = np.where(numbers > 5,numbers * 4,numbers)
print(conditional_array)
##basically its like if else, if numbers[i] > 5 , numbers[i] * 4 , else number[i] = numbers[i] only
conditional_arr = np.where(numbers > 5,"True","False")
print(conditional_arr)
## ternary operator man lete hain !

[ 1  2  3  4  5 24 28 32 36 40]
['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


combining array 

In [45]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
## what not to do : combined = arr1 + arr2
## returns summation of all the aij values

combined = np.concatenate((arr1,arr2))
print("combined array :" ,combined)

combined array : [1 2 3 4 5 6]


array compatibility 

In [47]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = np.array([1,2,3])

print("compatibility : ", a.shape == b.shape)


compatibility :  True


addition of a new column or a new row

In [52]:
original = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
new_row = np.array([10,11,12])
new_column = np.array([[20],[21],[22]])

with_new_row = np.vstack((original,new_row))
with_new_column = np.hstack((original,new_column))

print(with_new_row)
print("\n",with_new_column)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[ 1  2  3 20]
 [ 4  5  6 21]
 [ 7  8  9 22]]


Deletion 


In [54]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
deleted = np.delete(arr,2)   #its and array not the deleted element
print(deleted)

[ 1  2  4  5  6  7  8  9 10]
