this is a jupyter notebook

In [1]:
print("hello world")


hello world


In [2]:
import numpy as np

Creating array from list

In [4]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [9]:
arr_2d = np.array([[1,2,5],[4,5,6]])
print(arr_2d)

[[1 2 5]
 [4 5 6]]


In [10]:
list = [1,2,3,4,5]

In [17]:
py_multiplication = list * 2
arr_multiplication = arr_1d * 2
print(py_multiplication)
print(arr_multiplication)
print(arr_2d * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[[ 2  4 10]
 [ 8 10 12]]


In [19]:
py_list = [i for i in range(10)]
print(py_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [36]:
import time
start = time.time()
py_list = [i*2 for i in range(10)]
print("\ntime required for execution:",time.time()-start)

# start = time.time()
# py_arr = np.arange(10)
# print("\ntime required for execution:",time.time()-start)



time required for execution: 0.0026161670684814453


In [37]:
import time
start = time.time()
py_arr = np.arange(10)
print("\ntime required for execution:",time.time()-start)


time required for execution: 0.0025115013122558594
